version: "3"
services:
  app:
    container_name: cryptowatcher-app
    image: markov/cryptocurrencywatcher:0.1
    ports:
      - "8080:8080"
    environment:
      CONFIG_HOST: config-server
      MYSQL_HOST: db
    depends_on:
      - db
      - config-server
    restart: unless-stopped

  config-server:
    container_name: config-server
    image: markov/cloud-config-server:0.1
    ports:
      - "8888:8888"
    environment:
      MYSQL_HOST: db

  db:
    container_name: db
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cryptowatcher