version: "3"
services:
  app:
    container_name: cryptowatcher-app
    restart: always
    image: 200605030904/cryptowatcher-app
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cryptowatcher
      MYSQL_ROOT_PASSWORD: root