version: "3"
services:
  app:
    build: .
    container_name: cryptowatcher-app
    ports:
      - "8080:8080"
    environment:
      CONFIG_HOST: config-server
      MYSQL_HOST: db
    depends_on:
      - db
      - config-server
    restart: unless-stopped

  db:
    container_name: db
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cryptowatcher