spring:
  application:
    name: cryptocurrencywatcher
  profiles:
    active: cloud
  config:
    import: 'optional:configserver:http://${CONFIG_HOST:localhost}:8888/'
  cloud:
    config:
      enabled: true