spring:
  application:
    name: cryptocurrencywatcher
  profiles:
    active: cloud
  config:
    import: 'optional:configserver:'
    cloud:
      config:
        uri: http://localhost:8888/
        enabled: true
        failFast: true