spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cryptowatcher
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


multiplecoinsURL: https://api.coinlore.net/api/ticker/?id=80,90,48543
