spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cryptowatcher
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update


multiplecoinsURL: https://api.coinlore.net/api/ticker/?id=80,90,48543
logging:
  file:
    name: logging.log